import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import MainPages from './components/MainPages'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Synergy FE Test',
  description: 'Generated by Mahardika',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MainPages>
            {children}
          </MainPages>
        </Providers>
      </body>
    </html>
  )
}
